# Generated by Django 4.2.7 on 2024-02-23 09:12

from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    Student(name="Samian Saja", email="oteotegodok1945@gmail.com", document="22342342", phone="88805403414").save()

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
